### ISSUE TITLE
question about homography transformations 

### ISSUE THREAD

**Issue by noahzn** [cvg/glue-factory#66]
1. I notice that in this repo the variances of the homography transformations are smaller than in the SuperPoint repo. Have you tried more variances of transformations, such as perspective transformation?

2. If I have well aligned images taken by a fixed camera under different seasons and I want to train LG on my own dataset, is it correct that I need to write my own dataloader for training? Each pair of images is pixel aligned. Could you give more guidance on this? Thanks in advance.

**Comment by Phil26AT** [comment]
1. I have not compared it with SuperPoint, but the sampled homographies are pretty strong. You can adjust the diffulty [here](https://github.com/cvg/glue-factory/blob/main/gluefactory/datasets/homographies.py#L64).
2. Yes you would need to train your own data loader, but that should be quite straightforward. Since images are pixel-aligned, you could start from the homography dataset and initialize the homography to identity.

**Comment by noahzn** [comment]
Thank you very much!

**Comment by Astroooh** [comment]
How do I train LG, if two image pixels are not aligned one by one? Thank you.
